# Generated by Django 4.2.1 on 2023-05-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='price',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
